#Sample PVC for an application 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: jhooq-pvc
spec:
  volumeName: jhooq-demo-pv
  storageClassName: local: storage
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
resources:
  requests:
    storage: 1Gi