# ConfigMap and Secret for sample_webapp.yaml & sample_mongo
# Secret for confidential & secret data like User name and Password
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-password: UyFCXCpkJHpEc2I9
  mongo-username: YWRtaW4=