# ConfigMap and Secret for sample_webapp.yaml
# ConfigMap for non-confidential & non-secret data like DB URLs
# Secret for confidential & secret data like User name and Password
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-password: UyFCXCpkJHpEc2I9
  mongo-username: YWRtaW4=
