apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-storage
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
raclaimPolicy: Delete
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongo-pvc
spec:
  storageClassName: "demo-storage"
  accessModes: 
    - ReadWriteOnce
resources:
  requests:
    storage: 2Gi