apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  #serviceName: "mongo"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        command:
        - mongod
        - "--bind_ip_all"
        - "--replSet"
        - rs0
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  volumeClaimTemplate:
  - metadata:
    name: mongo-volume
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: demo-storage
      resources:
        requests:
          storage: 1Gi   
---

#Service(Headless Service) for the StatefulSet
# ClusterIP is None called as Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP # (Or) - name: mongo
      port: 8080/27017
      targetPort: 27017
  clusterIP: None